opx-config automation : phase 1
open-switch/opx-test pull request #25
Opened 2019-03-26 19:30 UTC by rakeshdatta

* Replaced the ip address, static route, mac, VLAN and LAG old configuration commands with new opx-config-commands
* Added l3-basic-functionality, data_vrf_basic, vlanConfig and lagConfig scripts.

2019-03-26 23:28 UTC, jeff-yin commented
Approved, but require @madhu222 's approval before merge

2019-03-27 22:56 UTC, jeff-yin commented
@madhu222 please review/approve?

2019-03-29 23:42 UTC, madhu222 commented
@rakeshdatta @Tejaswi-Goel Can you please run the sanity  and post the logs here?

2019-04-09 19:40 UTC, rakeshdatta commented
UPDATE: @Tejaswi-Goel is waiting for an available test bed for the sanity tests to be run.

2019-05-06 20:47 UTC, madhu222 requested changes
Can you please remove the spaces between tags ,always? There should not be any space in a block. Can you make changes in both opx-config-vlan and opx-config-lag

2019-05-06 20:52 UTC, madhu222 requested changes
I have mentioned where to remove the space in one test case. Please do it for all the test cases. And can you please remove the sanity from the failed test case for now?

2019-05-06 20:52 UTC, madhu222 commented on playbook/Forwarding/roles/span_mirroring/tasks/setup.yml
>      apt:
Remove the commented ones here

2019-05-06 20:52 UTC, madhu222 commented on playbook/L2/roles/vlanConfig/tasks/vlanConfig.yml
Remove the space here

2019-05-06 20:52 UTC, madhu222 commented on playbook/L2/roles/vlanConfig/tasks/vlanConfig.yml
Remove the space

2019-05-06 20:52 UTC, madhu222 commented on playbook/L2/roles/vlanConfig/tasks/vlanConfig.yml
> +
Remove the space

2019-05-06 20:52 UTC, madhu222 commented on playbook/L2/roles/vlanConfig/tasks/vlanConfig.yml
> +
Remove the space

2019-05-06 20:52 UTC, madhu222 commented on playbook/L2/roles/vlanConfig/tasks/vlanConfig.yml
> +
Remove the space,

2019-05-06 21:40 UTC, rakeshdatta commented on playbook/Forwarding/roles/span_mirroring/tasks/setup.yml
>      apt:
Not my change.

2019-05-07 17:46 UTC, madhu222 approved these changes
Looks good to me.

2019-05-08 18:24 UTC, jeff-yin commented
Needs DCO signoff...

2019-05-08 18:25 UTC, jeffyin-dell requested changes
Commit needs sign-off

2019-05-08 19:09 UTC, closed without merging